### ISSUE TITLE
Always connecting on 136.99

### ISSUE THREAD

**Issue by EncodedWasHere** [pierr3/VectorAudio#100]
Vector audio always connects on 136.99. Restarting Euroscope doesn't fix it and after having restarted it the error for incorrect password comes up

**Comment by pierr3** [comment]
What's your CID and are you connected to the network now? For the password error, just re-type your password in the settings for now and it should work

**Comment by EncodedWasHere** [comment]
1579020 and yes I am but not using vector audio right now because of the problem

**Comment by pierr3** [comment]
There is an issue with the latest release, you can download the previous one and that should work, I will fix it now

**Comment by pierr3** [comment]
Fixed in 1.6.1
