### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by RudiZhang** [pierr3/VectorAudio#106]
Hi, I think something is missing in 1.7.0 Beta-1. I can't even run the installer.

**Comment by maxlk96** [comment]
Same.
"The code execution cannot proceed because XXX was not found. Reinstalling the program may fix this problem"

It states this for the following:
- sfml-window-2.dll
- libcrypto-3-x64.dll
- libssl-3-x64.dll
- afv.native.dll

**Comment by Terminal-Rat** [comment]
Having the same issue

**Comment by zladatm** [comment]
> Same. "The code execution cannot proceed because XXX was not found. Reinstalling the program may fix this problem"
> 
> It states this for the following:
> 
> * sfml-window-2.dll
> * libcrypto-3-x64.dll
> * libssl-3-x64.dll
> * afv.native.dll

Had the exact same issue running the 1.7.0-beta.1 installer. 4 distinct windows error dialogue boxes. 1.5 is installed, windows 10 on an intel CPU.

**Comment by pierr3** [comment]
Will fix on next version, do not use the beta
