### ISSUE TITLE
Prompted for admin permission when launching on Windows

### ISSUE THREAD

**Issue by CruelHazbeast** [pierr3/VectorAudio#107]
Everytime I launch the app I'm prompted to grant admin access:

1. Is this expected?
2. Can this be avoided? e.g. is there some access that VA is requesting that can be turned off via settings?

For the usual reasons I run under a standard user account so would prefer to avoid granting admin access where possible.

**Comment by pierr3** [comment]
Hi, this is necessary because VectorAudio needs to monitor your keyboard even when the window is not in focus, otherwise it would not be able to pickup global push to talk. This cannot be done without admin permissions.

**Comment by CruelHazbeast** [comment]
Thanks for the answer but Vpilot uses the same function as it also constantly monitors the keyboard but I only need to give it admin permissions once and it hasn't ever asked for it again. Surely there is a way to code around the permission being asked everytime?

**Comment by pierr3** [comment]
Yes, that is something I should fix in the future.

**Comment by CruelHazbeast** [comment]
Cool, thank you very much!
