### ISSUE TITLE
macOS blurry font in title bar

### ISSUE THREAD

**Issue by redac** [pierr3/VectorAudio#11]
Software
- Vector Audio version: 1.33.1
- macOS Version: 12.3 (21E230)

Hardware
- MacBook Air M1 (13-inch, 2022)

Blurry title bar text :
<img width="794" alt="image" src="https://user-images.githubusercontent.com/20306749/159681902-8bbb48ad-27e6-4ae8-a1ba-0ed19ef3c0bc.png">
"Normal" title bar text in comparison : 
<img width="787" alt="image" src="https://user-images.githubusercontent.com/20306749/159682248-49af1522-5fa2-4d9e-9a3d-0f53c8c17756.png">

**Comment by redac** [comment]
Same thing with the menus : 
<img width="257" alt="image" src="https://user-images.githubusercontent.com/20306749/159684514-7f9c9add-079d-41fa-bc78-3c579a5af9d8.png">

**Comment by pierr3** [comment]
Probably linked to the NSHighResolutionCapable = false in the plist due to SFML not being DPI aware, solution would be to switch to SDL2 for long term

**Comment by pierr3** [comment]
Seems to not be an issue anymore on my end.
