### ISSUE TITLE
Add easier installation on macOS via Cask

### ISSUE THREAD

**Issue by flymia** [pierr3/VectorAudio#13]
Hi there!
First of all: GREAT software. It is important, that VATSIM becomes more open to other OSes, other than Windows. I've just tried your software on my M1 Mac Mini and it seem to be working great, even at this early stage of development.

I want to contribute to the software with my skills, so I started making a Cask for Homebrew, so that the software can easily be installed and upgraded using Homebrew.

I've created a repo with the cask [on here](https://github.com/flymia/homebrew-vectoraudio) and wanted to ask, if I should make PR, so that the Cask folder is implemented in the project here. That way, we could maintain the Homebrew tap and Cask in one repo, and users would not have to search for my repo. The cask works (just tested it).
Another idea would be, that we add my repo to the README, so that users see that the software can be installed via the Cask.

How are your thoughts about this? I would love to maintain the package for the software.

Cheers

Marc

**Comment by jonaseberle** [comment]
A great idea for users to get updates easily.

Just out of interest about distributing software for Mac because I am facing that problem in https://github.com/qutescoop/qutescoop/issues/48 and unfortunately none of the developers is using MacOS: 
Do you have to make an exception in Apple Gatekeeper for it be run? Is that common practice when using MacOS? Or should we open source developers apply for a digital signature from Apple? And is `.dmg` in general the preferred format.

Sorry for high-jacking this topic slightly. I am just so happy to meet a vocal and knowledgeable Mac user so I couldn't pass the opportunity to ask you.

**Comment by flymia** [comment]
Unfortonately I'm not a macOS developer myself, I'm just an "advanced macOS user", but I know what you are talking about.

> Do you have to make an exception in Apple Gatekeeper for it be run? Is that common practice when using MacOS?

To open the application I had to hold Shift and then right click -> Open. That's the only way for it to work right now. But many applications have this problem, since most open source developers for little tools, just like this, do not have a digital signature. You could try to apply for one, yes. I think that would fix the problem. But I also don't know, if you need to pay for this certificate.

I'd love to test some stuff for your projects, though.

**Comment by pierr3** [comment]
Thank you so much for this and yes please, feel free to create a PR and edit the readme in it too! You'll be duly credited of course. Totally agree that the cask route is the most convenient !

**Comment by pierr3** [comment]
> Unfortonately I'm not a macOS developer myself, I'm just an "advanced macOS user", but I know what you are talking about.
> 
> 
> 
> > Do you have to make an exception in Apple Gatekeeper for it be run? Is that common practice when using MacOS?
> 
> 
> 
> To open the application I had to hold Shift and then right click -> Open. That's the only way for it to work right now. But many applications have this problem, since most open source developers for little tools, just like this, do not have a digital signature. You could try to apply for one, yes. I think that would fix the problem. But I also don't know, if you need to pay for this certificate.
> 
> 
> 
> I'd love to test some stuff for your projects, though.

You do have to pay for an Apple dev account with signing certs. It's about 100$ per year. I'll probably get it at some point and when I do, I'll reach out to see how I can help :)

**Comment by flymia** [comment]
I think this can be closed.
