### ISSUE TITLE
Reportedly crackling voice output

### ISSUE THREAD

**Issue by jonaseberle** [pierr3/VectorAudio#18]
### Problem

During yesterday's session several pilots reported that my voice would "cut off" or be "crackling".

I checked with TeamSpeak's test function and verified that my microphone sound was clear (it plays back the audio to the output device).
![image](https://user-images.githubusercontent.com/1678001/176182671-47694766-1dd1-4554-a7fd-28608c3048a7.png)

I shortly disconnected and checked with VectorAudio's test, too. This looked also good.
![image](https://user-images.githubusercontent.com/1678001/176183430-9c49084c-a5e3-499e-a04b-c028bf10cb69.png)

I also checked that no CPU core was at 100% and that the network was not clogged.
I was able to receive voice from other ATC and pilots fine.
But after that I was out of ideas. Reconnecting did not improve the situation.

Do you have an idea what I could check next in such a situation?

### System

Manjaro, Linux 5.15, currently using `pipewire`(I switched to that as a primary sound system because in my previous attempted session with `pulseaudio` I was not able to get any microphone output)

Bluetooth audio headset
![image](https://user-images.githubusercontent.com/1678001/176187558-275f4a7b-cb17-41fd-9217-64b0d65a2bf8.png)

Currently these VectorAudio settings:
![image](https://user-images.githubusercontent.com/1678001/176186665-daf16597-3496-4553-a114-65f6551e9414.png)

**Comment by jonaseberle** [comment]
I am closing this since that is most possibly unrelated to VectorAudio. 
I've seen it mentioned as a regression with pipewire and bluetooth somewhere in a changelog that ought to be fixed by now (I can't find it anymore though).

**Comment by pierr3** [comment]
I think the ALSA backend might be culprit there, it’s not very stable, this
is all due to the library afv_native uses.
