### ISSUE TITLE
Feature request: Allow listening to my sound output 

### ISSUE THREAD

**Issue by jonaseberle** [pierr3/VectorAudio#19]
### Problem

I am looking for reassurance that my voice is working when starting a controlling session. I am currently doing "radio checks" on other controller's frequency because I am quite regularly not audible.

I am able to check that the microphone works in general with other programs, but I am currently not able to "hear" what VectorAudio "hears".

I would really like to listen to my voice - also to hear the effect of these settings:
![image](https://user-images.githubusercontent.com/1678001/176189129-a6ccf5be-9ed0-4f0a-8320-bd08359bab56.png)

Related: https://github.com/pierr3/VectorAudio/issues/18

### Suggestion

A "Loopback" function:

Do you see any technical possibility to listen in to the microphone input before it is being sent to the audio server? 
`input -> VectorAudio -> output`

Or could we even listen in to our voice channel on the server while we are transmitting? Is that technically feasible?
`input -> VectorAudio -> audio server -> VectorAudio -> output`

**Comment by pierr3** [comment]
After reviewing, this is a bit hard to implement for now, I will close this and if at any point I have a burst of time I will try to implement.
