### ISSUE TITLE
EXC_BAD_ACCESS (SIGSEGV) when waking from sleep.

### ISSUE THREAD

**Issue by jlefkoff** [pierr3/VectorAudio#2]
Program crashes when it is running and computer is woken from sleep. MacOS log attached below.
[VectorAudioCrash.log](https://github.com/pierr3/VectorAudio/files/8026091/VectorAudioCrash.log)

**Comment by pierr3** [comment]
Should be fixed with commit 2c2d9afe4e31e0c3d15337ee32a608f1da962f77
