### ISSUE TITLE
macOS: Window stutters while moving

### ISSUE THREAD

**Issue by flymia** [pierr3/VectorAudio#20]
When moving the window around in macOS Monterey, it stutters and is not usable for around 1 second. There is no terminal output or any errors that get reported while moving the window (see the GIF). It's only a minor issue, but of course it would be cooler, as if this was fluid as all the other applications.

![CleanShot2022-07-03-14-04-08](https://user-images.githubusercontent.com/4712509/177038886-a33d0455-3eff-4641-a3a7-0ade9708a086.gif)

OS: macOS 12.4
Machine: Mac Mini M1 16 Gig

**Comment by pierr3** [comment]
Most likely something to do with the underlying renderer, can you check the CPU consumption of the app when moving it around?

**Comment by pierr3** [comment]
Closing this, feel free to ask to reopen if this still occurs or someone else experiences this!
