### ISSUE TITLE
CTD on start-up

### ISSUE THREAD

**Issue by KingfuChan** [pierr3/VectorAudio#22]
macOS 12.5, M2 MacBook Air 8CPU 8GPU 16RAM
Shows the following message when crashing:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               vector_audio [4877]
Path:                  /Applications/VectorAudio.app/Contents/MacOS/vector_audio
Identifier:            vector_audio
Version:               1 (1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-08-05 11:18:00.6331 +0800
OS Version:            macOS 12.5 (21G72)
Report Version:        12
Anonymous UUID:        AB8335AD-33FD-5043-57AC-8C45F69C82CF

Time Awake Since Boot: 4000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000018
Exception Codes:       0x0000000000000001, 0x0000000000000018
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [4877]

VM Region Info: 0x18 is not in any region.  Bytes before following region: 68719476712
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      commpage (reserved)        1000000000-7000000000   [384.0G] ---/--- SM=NUL  ...(unallocated)

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   vector_audio                  	       0x104d3cc18 afv_unix::updater::updater() + 556
1   vector_audio                  	       0x104d3cc14 afv_unix::updater::updater() + 552
2   vector_audio                  	       0x104c59520 main + 1000
3   dyld                          	       0x10536908c start + 520

Thread 1:
0   libsystem_kernel.dylib        	       0x1af662270 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1af69c83c _pthread_cond_wait + 1236
2   libc++.1.dylib                	       0x1af5eb320 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 100
3   vector_audio                  	       0x104caecc8 std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&) + 244
4   vector_audio                  	       0x104cbffb0 spdlog::details::mpmc_blocking_queue<spdlog::details::async_msg>::dequeue_for(spdlog::details::async_msg&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >) + 100
5   vector_audio                  	       0x104cbfe34 spdlog::details::thread_pool::process_next_msg_() + 128
6   vector_audio                  	       0x104cbfcf4 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, spdlog::details::thread_pool::thread_pool(unsigned long, unsigned long, std::__1::function<void ()>)::'lambda'()> >(void*) + 68
7   libsystem_pthread.dylib       	       0x1af69c26c _pthread_start + 148
8   libsystem_pthread.dylib       	       0x1af69708c thread_start + 8

Thread 2:
0   libsystem_pthread.dylib       	       0x1af697078 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x1af697078 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x1af697078 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x000000016b1ab630   x1: 0x0000000000000000   x2: 0x000000014ab00000   x3: 0x000000014ab69ae0
    x4: 0x00000000000000d0   x5: 0x000000014ab69ae0   x6: 0x000000000000000d   x7: 0x0000000000000001
    x8: 0x0000000000000000   x9: 0xc90dcdda174a0025  x10: 0x0000000000179f41  x11: 0x0000000000096600
   x12: 0x000000014ab00000  x13: 0x0000000000000000  x14: 0x00000000d86246b0  x15: 0x000000000005b9fe
   x16: 0x00000000000005b9  x17: 0x00000000000005b9  x18: 0x0000000000000000  x19: 0x000000014ab66970
   x20: 0x000000014ab669a8  x21: 0x000000014ab669d8  x22: 0x0000000000000021  x23: 0x000000016b1ab648
   x24: 0x0000000000000030  x25: 0x000000014ab66990  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016b1ab6b0   lr: 0x0000000104d3cc14
    sp: 0x000000016b1ab600   pc: 0x0000000104d3cc18 cpsr: 0x20001000
   far: 0x0000000000000018  esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
       0x104c54000 -        0x105033fff vector_audio (1) <f01411fd-5dd5-381c-ad77-16a4105bfd07> /Applications/VectorAudio.app/Contents/MacOS/vector_audio
       0x105364000 -        0x1053c3fff dyld (*) <75627683-a780-32ad-ae34-cf86dd23a26b> /usr/lib/dyld
       0x1af65d000 -        0x1af694fff libsystem_kernel.dylib (*) <67f22904-88ed-3847-bbf0-5c4c599fd79e> /usr/lib/system/libsystem_kernel.dylib
       0x1af695000 -        0x1af6a1fff libsystem_pthread.dylib (*) <f32ff902-ba43-30b0-ad43-a2a8a9ff69fe> /usr/lib/system/libsystem_pthread.dylib
       0x1af5de000 -        0x1af644fff libc++.1.dylib (*) <ca366de6-c395-319a-b3ab-e22126d28394> /usr/lib/libc++.1.dylib
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=792.9M resident=0K(0%) swapped_out_or_unallocated=792.9M(100%)
Writable regions: Total=293.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=293.5M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               256K        2 
Activity Tracing                   256K        1 
CG backing stores                 3328K        4 
CG image                          1904K        2 
ColorSync                          544K       24 
CoreAnimation                       16K        1 
CoreGraphics                        16K        1 
CoreUI image data                  160K        1 
Dispatch continuations            64.0M        1 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                            92.8M       37 
MALLOC guard page                  192K       10 
MALLOC_MEDIUM (reserved)         120.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.1M        5 
Stack                             10.1M        5 
VM_ALLOCATE                       1120K       16 
__AUTH                            1774K      148 
__AUTH_CONST                      9217K      295 
__CTF                               756        1 
__DATA                            8109K      284 
__DATA_CONST                      10.3M      297 
__DATA_DIRTY                       602K      101 
__FONT_DATA                          4K        1 
__GLSLBUILTINS                    5176K        1 
__LINKEDIT                       579.5M        6 
__OBJC_CONST                      1244K      124 
__OBJC_RO                         83.0M        1 
__OBJC_RW                         3168K        1 
__TEXT                           213.3M      313 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
mapped file                      149.6M       18 
shared memory                      848K       13 
===========                     =======  ======= 
TOTAL                              1.4G     1719 
TOTAL, minus reserved VM space     1.3G     1719 

-----------
Full Report
-----------

{"app_name":"vector_audio","timestamp":"2022-08-05 11:18:00.00 +0800","app_version":"1","slice_uuid":"f01411fd-5dd5-381c-ad77-16a4105bfd07","build_version":"1","platform":1,"share_with_app_devs":1,"is_first_party":1,"bug_type":"309","os_version":"macOS 12.5 (21G72)","incident_id":"FEBA209A-9AB2-4122-9CE6-AA9B652F6633","name":"vector_audio"}
{
  "uptime" : 4000,
  "procLaunch" : "2022-08-05 11:18:00.5076 +0800",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,2",
  "procStartAbsTime" : 97030589173,
  "coalitionID" : 2184,
  "osVersion" : {
    "train" : "macOS 12.5",
    "build" : "21G72",
    "releaseType" : "User"
  },
  "captureTime" : "2022-08-05 11:18:00.6331 +0800",
  "incident" : "FEBA209A-9AB2-4122-9CE6-AA9B652F6633",
  "bug_type" : "309",
  "pid" : 4877,
  "procExitAbsTime" : 97033577707,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "vector_audio",
  "procPath" : "\/Applications\/VectorAudio.app\/Contents\/MacOS\/vector_audio",
  "bundleInfo" : {"CFBundleVersion":"1","CFBundleShortVersionString":"1"},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "crashReporterKey" : "AB8335AD-33FD-5043-57AC-8C45F69C82CF",
  "sip" : "enabled",
  "vmRegionInfo" : "0x18 is not in any region.  Bytes before following region: 68719476712\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      commpage (reserved)        1000000000-7000000000   [384.0G] ---\/--- SM=NUL  ...(unallocated)",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000018","rawCodes":[1,24],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000018"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":4877},
  "vmregioninfo" : "0x18 is not in any region.  Bytes before following region: 68719476712\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      commpage (reserved)        1000000000-7000000000   [384.0G] ---\/--- SM=NUL  ...(unallocated)",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":79864,"threadState":{"x":[{"value":6091879984},{"value":0},{"value":5548015616},{"value":5548448480},{"value":208},{"value":5548448480},{"value":13},{"value":1},{"value":0},{"value":14487461912898043941},{"value":1548097},{"value":615936},{"value":5548015616},{"value":0},{"value":3630319280},{"value":375294},{"value":1465},{"value":1465},{"value":0},{"value":5548435824},{"value":5548435880},{"value":5548435928},{"value":33},{"value":6091880008},{"value":48},{"value":5548435856},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4375956500},"cpsr":{"value":536875008},"fp":{"value":6091880112},"sp":{"value":6091879936},"esr":{"value":2449473542,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":4375956504,"matchesCrashFrame":1},"far":{"value":24}},"queue":"com.apple.main-thread","frames":[{"imageOffset":953368,"symbol":"afv_unix::updater::updater()","symbolLocation":556,"imageIndex":0},{"imageOffset":953364,"symbol":"afv_unix::updater::updater()","symbolLocation":552,"imageIndex":0},{"imageOffset":21792,"symbol":"main","symbolLocation":1000,"imageIndex":0},{"imageOffset":20620,"symbol":"start","symbolLocation":520,"imageIndex":1}]},{"id":79865,"frames":[{"imageOffset":21104,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":2},{"imageOffset":30780,"symbol":"_pthread_cond_wait","symbolLocation":1236,"imageIndex":3},{"imageOffset":54048,"symbol":"std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >)","symbolLocation":100,"imageIndex":4},{"imageOffset":371912,"symbol":"std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&)","symbolLocation":244,"imageIndex":0},{"imageOffset":442288,"symbol":"spdlog::details::mpmc_blocking_queue<spdlog::details::async_msg>::dequeue_for(spdlog::details::async_msg&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >)","symbolLocation":100,"imageIndex":0},{"imageOffset":441908,"symbol":"spdlog::details::thread_pool::process_next_msg_()","symbolLocation":128,"imageIndex":0},{"imageOffset":441588,"symbol":"void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, spdlog::details::thread_pool::thread_pool(unsigned long, unsigned long, std::__1::function<void ()>)::'lambda'()> >(void*)","symbolLocation":68,"imageIndex":0},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":3},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":3}]},{"id":79866,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":79867,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]},{"id":79869,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4375003136,
    "CFBundleShortVersionString" : "1",
    "size" : 4063232,
    "uuid" : "f01411fd-5dd5-381c-ad77-16a4105bfd07",
    "path" : "\/Applications\/VectorAudio.app\/Contents\/MacOS\/vector_audio",
    "name" : "vector_audio",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4382408704,
    "size" : 393216,
    "uuid" : "75627683-a780-32ad-ae34-cf86dd23a26b",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7237652480,
    "size" : 229376,
    "uuid" : "67f22904-88ed-3847-bbf0-5c4c599fd79e",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7237881856,
    "size" : 53248,
    "uuid" : "f32ff902-ba43-30b0-ad43-a2a8a9ff69fe",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7237132288,
    "size" : 421888,
    "uuid" : "ca366de6-c395-319a-b3ab-e22126d28394",
    "path" : "\/usr\/lib\/libc++.1.dylib",
    "name" : "libc++.1.dylib"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 7234584576,
  "size" : 3144695808,
  "uuid" : "ffede77c-d90b-366b-96f2-665c2f50ee59"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=792.9M resident=0K(0%) swapped_out_or_unallocated=792.9M(100%)\nWritable regions: Total=293.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=293.5M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               256K        2 \nActivity Tracing                   256K        1 \nCG backing stores                 3328K        4 \nCG image                          1904K        2 \nColorSync                          544K       24 \nCoreAnimation                       16K        1 \nCoreGraphics                        16K        1 \nCoreUI image data                  160K        1 \nDispatch continuations            64.0M        1 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                            92.8M       37 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)         120.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.1M        5 \nStack                             10.1M        5 \nVM_ALLOCATE                       1120K       16 \n__AUTH                            1774K      148 \n__AUTH_CONST                      9217K      295 \n__CTF                               756        1 \n__DATA                            8109K      284 \n__DATA_CONST                      10.3M      297 \n__DATA_DIRTY                       602K      101 \n__FONT_DATA                          4K        1 \n__GLSLBUILTINS                    5176K        1 \n__LINKEDIT                       579.5M        6 \n__OBJC_CONST                      1244K      124 \n__OBJC_RO                         83.0M        1 \n__OBJC_RW                         3168K        1 \n__TEXT                           213.3M      313 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                      149.6M       18 \nshared memory                      848K       13 \n===========                     =======  ======= \nTOTAL                              1.4G     1719 \nTOTAL, minus reserved VM space     1.3G     1719 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000430
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    }
  ],
  "experiments" : [

  ]
}
}

Model: Mac14,2, BootROM 7459.141.1, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M2, Apple M2, Built-In
Display: Color LCD, spdisplays_2560x1664Retina, Main, MirrorOff, Online
Memory Module: LPDDR5
AirPort: Wi-Fi, wl0: Apr  6 2022 05:55:54 version 20.90.45.0.8.7.118 FWID 01-e7138ff2
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.

**Comment by pierr3** [comment]
I have also had the same on my M1 MacBook Air. Think it’s related to http
calls and potentially openssl.

**Comment by KingfuChan** [comment]
> Body

Oh I think I figure out the problem. I'm using Clash http proxy, when I try to switch from http proxy to TUN proxy, I can open the app properly now.

**Comment by pierr3** [comment]
Feel free to reopen if you start experiencing this across all proxies
