### ISSUE TITLE
Feature Request: Customizable Frequency

### ISSUE THREAD

**Issue by KingfuChan** [pierr3/VectorAudio#25]
Native AFV allows to add stations without a definition from division facility engineer, by manually adding a frequency to it and AFV searches for nearby controllers. I'm wondering if it is possible to implement this feature because many TWR/GND/DEL/ATIS are not defined in some divisions. It'll be hard to do mentoring work without the possibility of adding stations by myself.

**Comment by pierr3** [comment]
This has been requested before but the official position from AFV devs is that all stations should be defined in the database. This is a bit annoying to implement so I would just strongly recommend that facility engineers define all frequencies instead. 

If anyone wants to do a PR for this, feel free!

**Comment by pierr3** [comment]
Duplicate of #6
