### ISSUE TITLE
Feature Request: RDF Support for EuroScope

### ISSUE THREAD

**Issue by KingfuChan** [pierr3/VectorAudio#26]
Firstly I'm really impressed on you vSMR project :)
Today I logged-in as a Center controller in an event and I found it hard to locate who's actually talking when my airspace was getting crowded...
I believe you know how RDF (https://github.com/chembergj/RDF) is currently working on ES. It needs a bridge reading the stdio of AFV client. Also AFV/VectorAudio and ES don't necessarily need to run on the same machine. So some day ago an idea occurred to me: Can VectorAudio send a message via HTTP to a pre-set network address, and modify the plugin above (or re-write?) to monitor a specific portal so that all RX can be displayed in ES?

**Comment by pierr3** [comment]
Thank you, glad you like it :)

Yes, I'd love to support it but the current RDF plug-in in EuroScope uses a windows only API for sending messages back and forth with AFV. If RDF is supported to allow for an HTTP or other more standard protocol, it'd be no problem to do that.

**Comment by KingfuChan** [comment]
Yes I know currently RDF is using WinAPI for monitoring AFV client messages. Actually the principle of displaying that circle is not difficult, and I've also got some experience in developing ES plugins, so I'm thinking if I could figure out how to build a HTTP server in the plugin, then this idea will become fully viable.

**Comment by LeoChen98** [comment]
> Thank you, glad you like it :)
> 
> Yes, I'd love to support it but the current RDF plug-in in EuroScope uses a windows only API for sending messages back and forth with AFV. If RDF is supported to allow for an HTTP or other more standard protocol, it'd be no problem to do that.


Is it possible to write an Euroscope plugin to listen the message from VectorAudio? It only requires a UDP broadcast on VectorAudio, and the plugin do the same things just like the afvbridge, so that the RDFplugin will work.

**Comment by pierr3** [comment]
v0.5.0 features the necessary interface on VectorAudio's side. See [this wiki page](https://github.com/pierr3/VectorAudio/wiki/Using-the-SDK) for details. Would be great if someone could create a plugin! Another plus from this implementation, as opposed to AFV Standalone, is that it should work on all EuroScope instances you have open, and not only the first one. Please do give feedback!

**Comment by jonaseberle** [comment]
Great, thank you!

Would we want to open an issue with https://github.com/chembergj/RDF/issues asking if they want to support that HTTP-interface, too? 
I guess the TopSky plugin includes the code from that plugin? 

Or do you think that makes no sense and we should go straight for a "VectorAudioRDFPlugin"?

**Comment by KingfuChan** [comment]
> Great, thank you!
> 
> Would we want to open an issue with https://github.com/chembergj/RDF/issues asking if they want to support that HTTP-interface, too? I guess the TopSky plugin includes the code from that plugin?
> 
> Or do you think that makes no sense and we should go straight for a "VectorAudioRDFPlugin"?

Actually if you look into how RDF now works with ES you will find out that it's the AFVEuroscopeBridge (https://github.com/AndyTWF/afv-euroscope-bridge) that's really triggering the RDF drawings. So my idea is to build a similar bridge plugin to send and receive HTTP request and deliver it in the same way where RDF will do the rest.

**Comment by KingfuChan** [comment]
Or simply using part of the codes from RDF and build another plugin is also viable. I would love to do so because I've got some experience with ES plugin developing, but I need to know how to make HTTP requests in this MFC C++ plugin in the first place :(

**Comment by pierr3** [comment]
I'm not actually sure AFVEuroscopeBridge has anything to do with it anymore. The RDF plugin itself communicates with EuroScope through another hidden window, the best way would be to take the code from RDF plugin, but run ProcessMessage on the return of an HTTP call that's done every second. You can see how I've been doing this using std::async and promises in this project: [here](https://github.com/vaccfr/CoFrance/blob/edb7864d5855b704dfb6e14e8b8a67db7576e430/CoFrancePlugIn.cpp#L589 ) and [here](https://github.com/vaccfr/CoFrance/blob/edb7864d5855b704dfb6e14e8b8a67db7576e430/CoFrancePlugIn.cpp#L508)

**Comment by pierr3** [comment]
> 

Idea

> Would we want to open an issue with https://github.com/chembergj/RDF/issues asking if they want to support that HTTP-interface, too?

I've created the issue, I believe it's better if it stays within one plugin, but I do not know how active the developer is, you can find it [here](https://github.com/chembergj/RDF/issues/9)! Go voice support!

**Comment by KingfuChan** [comment]
OK I'll get myself acquainted to those methods. Thanks for creating the new issue, though I think forking his repo then modify by ourselves would be better. I don't think the author is active from his front page.

**Comment by KingfuChan** [comment]
I've forked the RDF repo and is finishing the adaptation process, also added some new features. I'm looking at a first release in the few days.

**Comment by pierr3** [comment]
Amazing, thank you so much. I would highly recommend that you set the default of addressVectorAudio to "127.0.0.1:49080", as most users are likely to be using the software on the same machine and this would enable the plugin to be plug&play.

**Comment by jonaseberle** [comment]
I've just been testing it and it works pretty good already. 
Great job, thank you!

What I have done:
* I added the settings mentioned in https://github.com/KingfuChan/RDF#configurations. For my config (VectorAudio on Linux, EuroScope in wine) `RDF Plugin for Euroscope:VectorAudioAddress:127.0.0.1:49080` made it connect. (I added the other settings as well - not sure if necessary)
* Loaded the .dll via EuroScope OTHER SET -> Plugins... -> Load
* in EuroScope OTHER SET -> Plugins... I allowed the plugin to draw on types: "Standard ES radar screen" (+ everything else you have there, in my case the ["Ground Radar Display"](https://vatsim-scandinavia.org/forums/topic/3462-ground-radar-plugin-15/))
* Connected EuroScope (as observer)
* Connected VectorAudio and enabled some online frequencies
* Saw the message "RDF Plugin: Connected to VectorAudio/0.6.0" in the EuroScope messages
* Be very happy seeing circles around transmitting planes :)

Just some remarks:
* "Log" Messages are currently added to the "main" EuroScope messages. It would be great if they could go to their own "RDF" group. I mean like CCAMS is doing it here:
![image](https://user-images.githubusercontent.com/1678001/218272921-9ba24dda-ada1-49c2-9b91-488be32f38dc.png)
That would make it easier to find them. They are already very helpful for troubleshooting!
* The "poll interval" seems to be 1s at the moment. Some transmissions are too short to be picked up. It would be great if it could be much smaller (300ms?). Maybe a setting for it?
* Very minor issue: Currently transmissions are shown as "concurrent" even if they happen on 2 different frequencies or on different audio devices (because the VectorAudio SDK reports them like that). I don't know if that is improvable due to possible cross-coupling etc. The use case would be that you monitor stations around you on the SPK audio device.
* Would it be possible to set the radius of the circle in pixels rather than NM? For the ground I need a totally different radius in NM... (I don't know if that's easy with the EuroScope plugin API)

Maybe we should have an "issues" tab at the Github page at https://github.com/KingfuChan/RDF ?

Disclaimer: I have never really used AfV or any RDF plugin before.

**Comment by KingfuChan** [comment]
Hi, thanks for your opinion. Actually I'm working on a few items you just mentioned. In the next release I'll try to implement the following modifications.

> set the default of addressVectorAudio to "127.0.0.1:49080", as most users are likely to be using the software on the same machine and this would enable the plugin to be plug&play.

I've already added to my code with this default setting, which means there's no need to furthermore configure anything is localhost works perfectly for users. By default the plugin will behave just like the original RDF.

> * "Log" Messages are currently added to the "main" EuroScope messages.

This is actually intended to prevent disturbing messages in EuroScope. Basically all plugins will use the native "Messages" chat to display information.

> * The "poll interval" seems to be 1s at the moment. Some transmissions are too short to be picked up. It would be great if it could be much smaller (300ms?). Maybe a setting for it?

This will be examined later, because I've tested VectorAudio won't work properly if the interval is too short (too many simultaneous requests). Currently I'm using the OnTimer event in EuroScopePlugin SDK and it's forced to refresh every second. Later I may try to use threading for customizable poll interval.

> * Very minor issue: Currently transmissions are shown as "concurrent" even if they happen on 2 different frequencies or on different audio devices (because the VectorAudio SDK reports them like that). I don't know if that is improvable due to possible cross-coupling etc. The use case would be that you monitor stations around you on the secondary (SPK) audio device.

This is what the official AFV client is doing, and also neither can VectorAudio distinguish different devices and frequencies, sorry I don't think there's room for improvement.

> * Would it be possible to set the radius of the circle in pixels rather than NM? For the ground I need a totally different radius in NM... (I don't know if that's easy with the EuroScope plugin API)

Yes, I will add this to the next release.

Feel free to open an issue in my repo! I'll close this issue now. Thanks for the work from everybody!

**Comment by jonaseberle** [comment]
Thank you @KingfuChan!
You can enable issues in https://github.com/KingfuChan/RDF/settings - I think it is off by default for forks.

**Comment by jonaseberle** [comment]
Should we advertise it on https://forum.vatsim.net/tag/euroscope to get some more testing in?

**Comment by KingfuChan** [comment]
> You can enable issues

Done.

> Should we advertise it on https://forum.vatsim.net/tag/euroscope to get some more testing in?

I doubt that VectorAudio is not officially recognized by VATSIM yet (from an SUP friend of mine), which means advertising my plugin is OK but advertising VectorAudio may cause some other issues?

**Comment by pierr3** [comment]
I'm working on that. At stay tuned.

**Comment by pierr3** [comment]
I've lowered the SDK update rate to 300ms, and increased the number of workers in the SDK, this will be available in the next release, if you want to try and poll more frequently.

**Comment by KingfuChan** [comment]
> * The "poll interval" seems to be 1s at the moment. Some transmissions are too short to be picked up. It would be great if it could be much smaller (300ms?). Maybe a setting for it?



> I've lowered the SDK update rate to 300ms, and increased the number of workers in the SDK, this will be available in the next release, if you want to try and poll more frequently.

My work is done and a configurable poll interval is included in the newest (pre-release v1.3.2)[https://github.com/KingfuChan/RDF/releases/tag/v1.3.2]. Please check it out. If no serious problem with my new method I will change it to and official release.

Also to be noted by a friend of mine, is it possible to add a WebSocket method to proactively push transmitting pilots to the RDF client?

**Comment by pierr3** [comment]
I could explore the websocket solution in the future, not sure what the timeline looks like for now. I also need to refactor the code to detect multiple transmissions on one frequency, I will let you know! Thank you for the work.

**Comment by jonaseberle** [comment]
Thank you! It would be great to get that merged upstream.
