### ISSUE TITLE
PTT key

### ISSUE THREAD

**Issue by kodiakastu** [pierr3/VectorAudio#32]
My keyboard has F13 to F24 keys but only F13-f15 are recognized.

Is it a desirable behavior ?

**Comment by pierr3** [comment]
Yes, unfortunately, this is a limitation from the underlying SFML library, which should in the fututre support more input options. See https://github.com/SFML/SFML/pull/1235

**Comment by kodiakastu** [comment]
From what I'm reading, it's supported in the 2.6.x branch.

**Comment by jonaseberle** [comment]
To my knowledge, the mentioned Microsoft scancodes only standardize F1-F12.

**Comment by pierr3** [comment]
The next release upgrades to SFML 2.6 and supports more F keys
