### ISSUE TITLE
Wrong Frequency on Connect

### ISSUE THREAD

**Issue by cakequest** [pierr3/VectorAudio#34]
When initially connecting the frequency sometimes is off by 0.001. For example in the following screenshot the correct frequency for CZVR CTR is 133.700 but when connecting initially it connects to 133.699. 
![1A4D2ABF-97C7-4653-97FD-747A712E5533](https://user-images.githubusercontent.com/71202113/219972318-5d54e1ad-1250-4e9a-b7e3-28e9eb2a3ab1.png)

Deleting this frequency and re-adding it seems to fix the issue but it is a little bit annoying to have to do every time.

**Comment by pierr3** [comment]
Which client are you using to connect to VATSIM? This is really strange I will investigate.

**Comment by cakequest** [comment]
It's 133.700 in the ESE file. And correct, if the frequency is added manually there isn't any issue.

**Comment by pierr3** [comment]
I'll force some data cleaning in the next release to prevent this issue. Thanks for reporting!

**Comment by pierr3** [comment]
Version 0.7.0 addresses this, try it when it's done building!
