### ISSUE TITLE
libafv.so not found

### ISSUE THREAD

**Issue by c4181** [pierr3/VectorAudio#35]
When I run the prebuilt Ubuntu release I get the following error when running vector audio: 

./vector_audio: error while loading shared libraries: libafv.so: cannot open shared object file: No such file or directory

Using v0.6.0 and Ubuntu 22.04

**Comment by pierr3** [comment]
Can you open a terminal and try to run the below in the root folder of your vector_audio install?:

`patchelf --set-rpath \$ORIGIN:\$ORIGIN/./lib vector_audio`

**Comment by pierr3** [comment]
Closed for inactivity
