### ISSUE TITLE
Window black on Xwayland

### ISSUE THREAD

**Issue by weitcis** [pierr3/VectorAudio#36]
The window is completely black on Xwayland.

![image](https://user-images.githubusercontent.com/25654046/220377316-4e6c0697-df44-4aac-9268-6cac77ffa68d.png)

**Comment by weitcis** [comment]
![image](https://user-images.githubusercontent.com/25654046/220377685-8eb9cc98-e6ac-4f47-9637-9e3c53ab491c.png)
attached is some of the system information

**Comment by pierr3** [comment]
OpenGL 3.0+ is not supported on Asahi, you will need to wait till they implement that. This is most likely the core of the issue, recommend you use the macOS version.
