### ISSUE TITLE
Levelling

### ISSUE THREAD

**Issue by bcrockettt** [pierr3/VectorAudio#37]
It seems like pilots with their mic settings set too high are much louder in Vector than AFV client. Is leveling planned?

**Comment by pierr3** [comment]
Yes I have noticed that too, will need to do some filtering.

**Comment by pierr3** [comment]
Has anyone experienced the opposite, where some are much quieter? I will implement a limiter to avoid those high volumes.

**Comment by bcrockettt** [comment]
Very rarely.

**Comment by pierr3** [comment]
Although not fully fixed, I've tweaked some settings, let me know if this seems better or no different.

**Comment by bcrockettt** [comment]
It's better. Pilots that have their audio input set too high loud are still distorted, but they no longer far louder than properly configured pilots.

**Comment by pierr3** [comment]
Great, the next update will also have further tweaks, please let me know when it releases what you think

**Comment by pierr3** [comment]
Further tweaks have been added in v1.1.0, let me know what you think

**Comment by KingfuChan** [comment]
I didn't make any comparisons, but it seems those loud crews are still loud
