### ISSUE TITLE
[REQUEST] Show last received freq & callsign

### ISSUE THREAD

**Issue by BasBuur** [pierr3/VectorAudio#4]
Thanks for the software, works great!

It'd be very nice if we can see the latest received frequency & callsign somewhere in the UI just like with the official client. Especially for muted mics / rogue pilots it's very handy information to have.

**Comment by pierr3** [comment]
Thanks for using it! I added the last received callsigns in [010867b](https://github.com/pierr3/VectorAudio/commit/010867b79f19da14aeac82b488110c8957796698)

**Comment by BasBuur** [comment]
You're a star. Thanks, I appreciate it!
