### ISSUE TITLE
UI reacting to input across desktops

### ISSUE THREAD

**Issue by Ibot02** [pierr3/VectorAudio#40]
I am using Ubuntu 22.04 with GNOME on X11.
To save screen space, I usually have euroscope on full screen and VectorAudio on a second desktop of the same monitor that I switch between.

However, I noticed that VectorAudio sometimes reacts to clicks (setting gain volume, opening the license file or toggling TX or even disconnecting me) while I am still on the desktop with euroscope on it.
Not every click does get picked up, but it's often enough that it's pretty easy to reproduce. I have tested and confirmed the issue still exists on VectorAudio v0.7.0.

**Comment by jonaseberle** [comment]
I guess that's an error in X11 that has nothing to do with VectorAudio.
I also use 2 screens with X11 and haven't noticed any problems.

**Comment by pierr3** [comment]
Agreed, probably X11 error, please reopen if someone else can reproduce
