### ISSUE TITLE
Scaling under Wayland

### ISSUE THREAD

**Issue by weitcis** [pierr3/VectorAudio#41]
![image](https://user-images.githubusercontent.com/25654046/227438742-d766d7be-ac28-41c0-b9bd-3e32dcf88ae7.png)

Texts are too small to be readable when it is run under wayland through Xwayland.

**Comment by jonaseberle** [comment]
Is this with some HighDPI setting? It kind of looks like it to me.

**Comment by weitcis** [comment]
> Is this with some HighDPI setting? It kind of looks like it to me.

Yes.

**Comment by pierr3** [comment]
VectorAudio is not DPI aware due to the fact SFML also isn't. On macOS we set a specific flag to disable HighDPI rendering for the specific application, suggest you do the same. This will not be fixed until an updated to SFML is pushed.
