### ISSUE TITLE
Unable to identify my PTT device

### ISSUE THREAD

**Issue by RudiZhang** [pierr3/VectorAudio#44]
![image](https://github.com/pierr3/VectorAudio/assets/40914896/6dab3dcf-c177-4045-be2e-071dae5329bf)
![image](https://github.com/pierr3/VectorAudio/assets/40914896/d37a9c28-0003-4833-95a1-5ed32fec4af7)

Hi, the problem is as the screenshot above. I tried to set PTT in VectorAudio but nothing happened when I was pushing my PTT button. But worked for AFV.

**Comment by jonaseberle** [comment]
Please add more info (vector_audio.log, your operating system [since AfV works for you, you are probably on Windows?], your PTT device type).

That screenshot does not look like VectorAudio?

And just out of interest: If AfV works for you, why do you want to use VectorAudio?

Related: #39

**Comment by RudiZhang** [comment]
[vector_audio.log](https://github.com/pierr3/VectorAudio/files/11625203/vector_audio.log)

Windows 11 - 22H2 - 22621.1778

well, I don't know where should I find my PTT type

The first screenshot is from AFV, which shows AFV can identify my PTT normally

for the question: better than AFV XDXD

**Comment by RudiZhang** [comment]
Oh wait I think I found the device type: sound, video and game controllers
Manufacture: Generic USB Audio
Localtion: 0000.0014.0000.009.001.003.000.000.000

**Comment by jonaseberle** [comment]
That looks like a joystick device. Does it work with another joystick?

**Comment by RudiZhang** [comment]
> That looks like a joystick device. Does it work with another joystick?

Sorry for the late, It works with TCA.

**Comment by RudiZhang** [comment]
![image](https://github.com/pierr3/VectorAudio/assets/40914896/469adb55-0de7-40e0-a673-744e816880e2)

Or maybe any chance to change the config file manually?

**Comment by jonaseberle** [comment]
Maybe try another tool that translates your joystick buttons into key presses.
This one seems to be good for Windows: https://joytokey.net/en/
https://www.youtube.com/watch?v=MxW5ZC4lKrk

**Comment by pierr3** [comment]
VectorAudio uses SFML for controller detection, it is possible that it does not support this specific driver for your PTT, try the solution provided by @jonaseberle! You should also try to disconnect any other joysticks and see if VectorAudio picks your headset PTT up. You can edit the config manually, and more likely the value that will need to change is joyStickId, where you should try and find the right ID. joyStickPtt is likely to be 1 or 0 in your case.

**Comment by RudiZhang** [comment]
> Maybe try another tool that translates your joystick buttons into key presses. This one seems to be good for Windows: https://joytokey.net/en/ https://www.youtube.com/watch?v=MxW5ZC4lKrk

will try that



> VectorAudio uses SFML for controller detection, it is possible that it does not support this specific driver for your PTT, try the solution provided by @jonaseberle! You should also try to disconnect any other joysticks and see if VectorAudio picks your headset PTT up. You can edit the config manually, and more likely the value that will need to change is joyStickId, where you should try and find the right ID. joyStickPtt is likely to be 1 or 0 in your case.

Thanks for the help!

**Comment by pierr3** [comment]
Closed, please let us know if you still face issues
