### ISSUE TITLE
Unable to hear

### ISSUE THREAD

**Issue by sk0941** [pierr3/VectorAudio#45]
I recently did a hardware upgrade and now I can't hear things through Vector Audio, none of my transmissions are coming through either. It looks like I'm transmitting but nothing is coming through. 

I also tried to change the settings in the config.toml file to set my Vjoy key as the PTT but Vector Audio doesn't seem to pick up on any of the changes I make, be that to a real joystick or not. But changes made in the app are reflected in the config file. 

If some log files are needed tell me which ones.

**Comment by sk0941** [comment]
I can add that I'm able to transmit and people can hear me, but I can't hear anything, it's not even picking up that it's receiving

**Comment by sk0941** [comment]
[vector_audio.log](https://github.com/pierr3/VectorAudio/files/11738634/vector_audio.log)

Here's the log file, I've gotten pas the setting as Vector Audio now recognises the Vjoy key in the settings menue all of a sudden. When I first sign in with Vector the for Rx is just like someone is clicking their mike and then it goes silent and I won't see another Rx for that session, but I can still transmit somehow. 

I attached the log file

**Comment by pierr3** [comment]
Nothing apparent in the log file, I will try to push a new update and see if it helps

**Comment by pierr3** [comment]
Try running the software as admin! I have no precise idea as to what is happening. Also try the next update to be released soon.

**Comment by sk0941** [comment]
I'm at a loss, I installed the latest update but I got the same error. I can transmit, but the first transmission I receive sounds just like someone clicks their PTT and after that I'm not receiving anything

**Comment by pierr3** [comment]
Your log file shows you may have 4 different audio backends. Can you try to switch "audio api" in the settings and try with the various options available?

**Comment by sk0941** [comment]
Did some testing but no change. with Default I can transmit but not hear. WASAPI, can receive the first click but not transmit. DirectSound and WInMM gives the error "Error starting audio devices. Please check your log file for details. Check your audio config"

Attached an updated log file
[vector_audio.log](https://github.com/pierr3/VectorAudio/files/11951473/vector_audio.log)

**Comment by pierr3** [comment]
There are no obvious hints in your log file. By any chance, do you use xPilot and are you facing any similar issues? Can you also try reinstalling your audio drivers for your devices? The hardware change is probably the issue, and this is maybe an issue to upstream to miniaudio. You can also try to install JACK, and then retry using that backend: https://jackaudio.org/downloads/

Sorry for all the steps and thanks for your help in troubleshooting this!

**Comment by sk0941** [comment]
Not using xPilot, vPilot doesn't have these issues since the hardware change, neither does AFV. I tried installing JACK but Vector still crashes when I try to select it in the settings. 

I haven't tried reinstalling audio drivers yet so I'll get back once I've tried that

**Comment by sk0941** [comment]
I tried with a different set of speakers plugged directly into the 3,5mm jack with the same result. I've tried finding the drivers for my main device  , a HyperX Quadcast which is a USB connection but I run my headset through the 3,5mm jack on the mic. There are no specific drivers for that device other than the default windows drivers

**Comment by sk0941** [comment]
The issue still persists in v1.2.1

**Comment by pierr3** [comment]
Can you try using your 3.5mm headset as mic for both input devices? There might be an encoding issue with your mic since it seems to have a character miniaudio does not recognise.

**Comment by sk0941** [comment]
I tried using the 3,5mm for both mic and headset, got the same result, attached the latest log file.

[vector_audio.log](https://github.com/pierr3/VectorAudio/files/12034100/vector_audio.log)

**Comment by pierr3** [comment]
Give the latest version a try!

**Comment by sk0941** [comment]
I gave it a try, the result is the same as before :( I'm really lost as to why, I can't come up with a logical reason as to why upgraded hardware should cause the software to not be able to receive transmissions when everything else works.

**Comment by sk0941** [comment]
Issue persists in 1.3.2 :(

**Comment by sk0941** [comment]
I've tried uninstalling and deleting everything that has to do with Vector from the registry but to no avail

**Comment by sjames1066** [comment]
I'm also having the exact same issue as @sk0941 - please see attached log file :) 

After I connect, I disconnect and then cannot reconnect. I have to force quit the program in Task Manager in order to be able to start the program again. Have tried running as Admin both the installer and exe with no luck. 

[vector_audio.log](https://github.com/pierr3/VectorAudio/files/12433081/vector_audio.log)

**Comment by pierr3** [comment]
Thanks for the report and log, will investigate

**Comment by sjames1066** [comment]
[vector_audio.log](https://github.com/pierr3/VectorAudio/files/12470337/vector_audio.log)

Issue still persists with v1.4.0

**Comment by pierr3** [comment]
@sjames1066 can you describe the issue in details, your audio setup, and what setup you tried ? Still have failed to pinpoint this exactly. Thanks!

**Comment by sk0941** [comment]
Yea, issue still persists for me too

**Comment by pierr3** [comment]
Happy to report we have found the source bug for this, and the next release should address it

**Comment by pierr3** [comment]
Release has been pushed, and now should work! This took a lot of debugging, please let me know if it does not work, otherwise happy controlling!
