### ISSUE TITLE
distorted audio when processing is disabled

### ISSUE THREAD

**Issue by kpx1894** [pierr3/VectorAudio#47]
Hi,

Disabling Audio Postprocessing ("Off") appears to be ineffective.

BR,
K.

**Comment by pierr3** [comment]
Can you clarify whether turning off audio post processing distorts the audio, or are you trying to turn it off because you have distorted audio with it? Can you also describe the distortion and situations in which it occurs?

**Comment by kpx1894** [comment]
Hi, I am attempting to disable audio processing to focus on listening to audio content. Here's how it sounds with Vector Audio: https://youtu.be/91U5qc6Y5PU - there is background hissing, and the voice sounds radio-like. Meanwhile, the same controller with Audio for Vatsim: https://youtu.be/XCm6DIQfZg8 (starts around 0:18 until YouTube finishes trimming) produces just plain, recorded speech.

**Comment by pierr3** [comment]
Thank you for the detailed report! I'll take a look
