### ISSUE TITLE
v 1.2.0 Error 1000

### ISSUE THREAD

**Issue by bcrockettt** [pierr3/VectorAudio#49]
Getting this after upgrading to 1.2.0.

![image](https://github.com/pierr3/VectorAudio/assets/125828378/d3c647e3-b374-4337-8394-b45203c5b0aa)

**Comment by bcrockettt** [comment]
Windows 11.

**Comment by pierr3** [comment]
Any chance you have the .log? Does this occur straight on launch or through specific actions?

**Comment by bcrockettt** [comment]
Straight on launch (first two times), third time launch did not and now it's working fine. Here's the relevant log snippet:

![image](https://github.com/pierr3/VectorAudio/assets/125828378/202b70ec-6d5d-4807-bd6e-4cf610bcaeac)

**Comment by pierr3** [comment]
Strange, still facing an issue or does it still randomly behave this way? Were you recently connected as a pilot before logging on as a controller?

**Comment by pierr3** [comment]
Try v1.2.1: https://github.com/pierr3/VectorAudio/releases/tag/v1.2.1

**Comment by pierr3** [comment]
Please report if this still occurs
