### ISSUE TITLE
(Feature Request) Add support for the use of keys F13-F24

### ISSUE THREAD

**Issue by sunriselabs-digital** [pierr3/VectorAudio#51]
Many controllers use the F13-F24 keys as their AFV push to talk, as it does not interfere with typing text or other application functions. When trying to map a key greater than F12 in Vector, the software is unable to recognize that the key has been pressed allowing it to be bound to the push to talk. AFV does support the functionality and would make Vector just that much nicer to use.

**Comment by pierr3** [comment]
This should have been fixed since v1.2.0 since SFML got updated to support scan codes. Make sure you have the latest version and run the program as admin! 

Please let me know if it still does not work
