### ISSUE TITLE
Feature Request: API for frequency inquiry

### ISSUE THREAD

**Issue by KingfuChan** [pierr3/VectorAudio#52]
Would like to know is there any possibility to build an API which returns the current RX and TX channels and frequencies?

E.g. -> "/RX" and "/TX", returns "xxxx_CTR:120.300,xxxx_APP:122.250,xxxx_TWR:118.375"

I'm considering building another plugin to do the work of [AndyTWF/afv-euroscope-bridge](https://github.com/AndyTWF/afv-euroscope-bridge).

**Comment by pierr3** [comment]
Done! In the same format as you gave except lowercase for the urls (/tx and /rx). It will be available in the next release

**Comment by KingfuChan** [comment]
Wow! That's quick. Though I'm still doubting whether to add this feature to a new plugin or just into my RDF. Is there any potential delays when multiple requests are sent at the same time?

**Comment by pierr3** [comment]
Yes, but only if you rapidly spam the API, there should be 16 workers available to handle 16 simultaneous calls, but be gentle!

If you integrate it into the RDF plugin, I would be more than happy should you wish to package the plugin DLL with the application. Thank you for your work!

**Comment by jonaseberle** [comment]
Thank you both for working on that! 

It would be great if these changes could be made as a pull request to the original plugins so that they ultimately support would support AfV + VentorAudio.

That way the packages that ARTCCs provide to their users could support both without the users having to change the plugins.

**Comment by KingfuChan** [comment]
> It would be great if these changes could be made as a pull request to the original plugins so that they ultimately support would support AfV + VentorAudio.

actually my RDF does support the official AFV, but since there haven't been any activities on the original repo and I basically rewritten the plugin so I think a PR may somehow do more damage. So I just keep my RDF there. Also to be noted, many TopSky users don't need an extra RDF plugin since it's already integrated though it's not adapted to VectorAudio.

As for the bridge plugin, the original repo is also silent for 3 years. But there was some progress [PR#2](https://github.com/AndyTWF/afv-euroscope-bridge/pull/2) by its author, which is neither being developed nor been merged to main branch. It is also a major update, which makes me doubt the propriety to start a new branch and finish it then pull it back.

**Comment by pierr3** [comment]
Closing this as we should be all good, let me know if not!
