### ISSUE TITLE
Feature request: Dynamic Audio channels

### ISSUE THREAD

**Issue by MatisseBE** [pierr3/VectorAudio#56]
It's quite a far-reaching one - so take it for what it is.

It's always bothered me that there's no good way to set up audio such that both controller-to-controller coordination is audible, as well as the pilot who for sure will give you thát very important call when you're coordinating.

What if the application could control the audio channels dynamically? 
When it detects sound from a certain application (Discord/ES/TS), it changes the sound output from stereo to only one side.
This way, you can focus yourself on either the left or right channel - or simply here both at the same time. 

Ideally it should be able to reroute other application's audio for the best effect - but for this I would like to refer back to the first sentence of this post. 

If you're ever find yourself crazy enough, I think this code might help: https://github.com/bozbez/win-capture-audio - It's C++ code for an OBS plugin that captures individual application's audio.

**Comment by MatisseBE** [comment]
> I have set it up so that VectorAudio (headset) is on the left headphone and left speaker and TeamSpeak (controller-controller) + VectorAudio (speaker) on the right ones.

That's exactly what I don't like, it's just not comfortable. Besides, if my ears are going deaf because of VATSIM, I'd like both to degrade at the same rate lol. 

In all seriousness, point taken. A generic audio routing application would suit more people and more purposes. Unfortunately, that also means it will likely never come to fruition.

**Comment by jonaseberle** [comment]
> Unfortunately, that also means it will likely never come to fruition.

You or someone can build it for your audio system.

2 stereo in, 1 stereo out – dampen the volume of the "non-prio" app if the "priority" app also has level on that left/right channel.
It's similar to what audio production often does with the bass drum (when it hits other channels get suppressed) - they call it "side chaining".

**Comment by pierr3** [comment]
Would love that as well and think it would be very useful. However this is definitely way outside of the scope of this application.

VectorAudio is more of a stopgap measure until we get more cross platform controller clients, so when it gets to the stability level I want, it'll probably switch to LTS with a freeze of major development. 

I would, however, implement any system which would signal to another application that audio is incoming, if such an audio router application would require such signals. I would only do so if it can be done cross platform out of continuity and design philosophy. Let me know if you find anything that would work!

**Comment by jonaseberle** [comment]
Sorry, I couldn't stop myself. There's also hardware for that. I just found https://thepillpedal.com/ - you'd need 2 of them and some self-soldered cabling. Ok, it is getting ridiculous :)
My MPC Live could also do it, but that's even more ridiculous.

Software:
I guess we are blessed on Linux with ready-made little apps that can be chained together. For that project I would start with 2x https://lsp-plug.in/?page=manuals&section=sc_compressor_mono (the standalone LSP plugins). Such things must exist for other audio systems, too.

**Comment by pierr3** [comment]
Closing this as, although this would be amazing, is out of scope of this program.
