### ISSUE TITLE
Console window opens in background when running Windows .exe

### ISSUE THREAD

**Issue by caspianmerlin** [pierr3/VectorAudio#57]
Blank console window. When I have had this issue in the past it was because I needed to specify I was compiling for Windows subsystem, but not sure how to do that in C++.

**Comment by pierr3** [comment]
Apologies, overlooked this, will push a hot fix soon.

**Comment by pierr3** [comment]
A hotfix has been released, you can download the 1.3.1a installer under the 1.3.1 release and this will be fixed!
