### ISSUE TITLE
v1.3.1 on MacOS crashes when clicking connect

### ISSUE THREAD

**Issue by kmoberg** [pierr3/VectorAudio#58]
Hey,

Haven't used Vector Audio in a while, so upgraded from a pre v1 version to v1.3.1 by overwriting the existing app file in /Applications. 

The application launches fine, and I gave it the permissions it asks for, but when clicking "Connect" in Vector audio, the application crashes. Below is the macOS Crash report as well as the `vector_audio.log` file.

MacOS Crash report: http://i.kmoberg.io/6hnmC8
`vector_audio.log`: http://i.kmoberg.io/XpLQj1

**Comment by pierr3** [comment]
Seems to be an issue with opening your audio devices! Can you try to reset your audio settings to new values, and then running the mic test? Thanks!

**Comment by kmoberg** [comment]
> Seems to be an issue with opening your audio devices! Can you try to reset your audio settings to new values, and then running the mic test? Thanks!

Switching to a different audio device, running the mic test, then changing it back did indeed solve the issue! Thank you!
