### ISSUE TITLE
VectorAudio will not start on Windows without Administrator privileges

### ISSUE THREAD

**Issue by DhruvK1985** [pierr3/VectorAudio#59]
WIn 10 Home. VectorAudio will not launch unless explicitly set to "Run as Administrator". Not ideal practice with UAC.

**Comment by pierr3** [comment]
This is normal and necessary, as the software needs to be able to monitor keyboard inputs in the background for global push to talk.

**Comment by pierr3** [comment]
Will be fixed on next release.
