### ISSUE TITLE
Feature request: "minimalism" view mode

### ISSUE THREAD

**Issue by Pirx-ThePilot** [pierr3/VectorAudio#61]
Hi,

First of all thank you for your great contribution for VATSIM community - I've just started using VectorAudio under Ubuntu 22.04.

What I miss, comparing to AFV, is kind of "minimalism" view, especially when you use just one screen, where the **app size is minimal** that you can see only some basic things like:
- TX, RX squares
- Last station callsign
- Connect / Disconnect buttons

Thanks for considerations!

**Comment by pierr3** [comment]
Good suggestion, might implement in the future and happy to review any PR!

**Comment by neilenns** [comment]
I'd love to see this as well!

**Comment by pierr3** [comment]
This has been implemented in [TrackAudio](https://github.com/pierr3/TrackAudio), please head over there to enjoy this!
