### ISSUE TITLE
Feature Request: Distinct disconnect sound

### ISSUE THREAD

**Issue by ogruetzmann** [pierr3/VectorAudio#66]
With the AfV issues today, I realized that disconnects can easily go unnoticed when one is not monitoring the interface closely. A distinct sound would be great for these occasions, maybe a popup as well.

**Comment by pierr3** [comment]
Good idea, will be mildly complicated as VectorAudio itself has no audio capabilities, but the underlying library does.

**Comment by ogruetzmann** [comment]
A distinct on-top popup in bright red might also do the trick, I guess :)
