### ISSUE TITLE
Crash on OS X 14.0 Beta

### ISSUE THREAD

**Issue by aselder** [pierr3/VectorAudio#67]
Vector Audio crashed immediately on hitting the Connect button. 

Crash Log attached.

[Crash.log](https://github.com/pierr3/VectorAudio/files/12436200/Crash.log)

**Comment by pierr3** [comment]
Thanks for the report, which Beta version are you running ? I am on public beta 3 and it works. Will look, I have my suspicions.

**Comment by pierr3** [comment]
Closed as final release is published which seems to work fine
