### ISSUE TITLE
Add the option to assign keys F13-F24 to PTT

### ISSUE THREAD

**Issue by Jannis-D** [pierr3/VectorAudio#68]
Add the option to assign keys F13-F24 to PTT. This is useful for additional Hardware. Currently I have to use AfV as workaround for me.
Thank you!

**Comment by pierr3** [comment]
Thus should already be the case. Can you please share your system version and other details about your OS configuration?

**Comment by pierr3** [comment]
Please re-open and update if you get the chance. Closing as stale.
