### ISSUE TITLE
After reconnect TX went to the wrong frequency

### ISSUE THREAD

**Issue by jonaseberle** [pierr3/VectorAudio#7]
In this setting
![image](https://user-images.githubusercontent.com/1678001/155853812-128c0e4d-70e8-40a2-9869-3844e31a81c0.png)

I was disconnected from VATSIM with EuroScope and after reconnect I was not reachable on voice.
So I manually disconnected VECTOR and connected again.

After that my transmissions went to the EDDS_TWR frequency ;)
Unchecking all boxes and checking them again fixed it.

I love that new visual style btw! :) And the secondary voice output SPK is a godsend! Thank you!

**Comment by pierr3** [comment]
Thanks for the feedback, really happy that you like the UI. Yes this is an important improvement, I need to perform some cleanup in case of a disconnection, which results in weird bugs at the moment.

**Comment by pierr3** [comment]
The latest version should address the majority of this, except that the number of transceivers above SPKR will not refresh and show XX. This will require a more challenging fix in the future. Keeping this open.

**Comment by jonaseberle** [comment]
851088ed6f3b003aa3b933c132255d10eb8cb290 / [v0.3.0-851088e](https://github.com/pierr3/VectorAudio/releases/tag/v0.3.0-851088e):

After disconnect all previously shown stations are cleared. I can add them again after reconnecting. (I've just tested now as observer)

So I think the immediate problem is fixed.

**Comment by jonaseberle** [comment]
I just had a long session and also a reconnect in between.
I cannot reproduce it anymore. Thank you @pierr3!
