### ISSUE TITLE
High resolution screen support.

### ISSUE THREAD

**Issue by ITheLestI** [pierr3/VectorAudio#70]
Hello. Recently I downloaded Vector Audio and found that it is pretty hard to use on my laptop. I have 2560x1600 14" monitor and I use 175% scaling in windows, but it don't affect button size in VectorAudio UI. Also there is no option to change interface scale in a program itself. So please add one of this features to make VA usable on my device, please.
![image](https://github.com/pierr3/VectorAudio/assets/55897854/d61779e3-a3f7-4ab6-a73c-e385836b4d80)

**Comment by pierr3** [comment]
Unfortunately, this is a current limitation of SFML used as a backend, and will not be fixed until they do. It is supposed to be fixed on macOS retina displays but not others. Try and use a resolution scaling of 200% and see how that behaves
