### ISSUE TITLE
New Feature: Custom Frequency

### ISSUE THREAD

**Issue by ITheLestI** [pierr3/VectorAudio#71]
I know that in AFV you can type some callsigns (for example XXXX_ATIS) and AFV offers you to type in custom freq to listen. This is useful when freq of certain position has changed and controller works not on that freq wich inserts if we type his callsign.

**Comment by pierr3** [comment]
This is not currently planned, as the design should be that stations are properly defined in the database. It may get added in a later update but no plans currently.
