### ISSUE TITLE
Bug: Fake "Could not find station in database"

### ISSUE THREAD

**Issue by ITheLestI** [pierr3/VectorAudio#72]
When you search for "UUEE_GND" for example, application returns error: Could not find station in database, **but** afterwards creates 2 new stations in client, as it supposed to do.

**Comment by pierr3** [comment]
That's technically normal, it means your FE has not properly setup the database and did not name statiosn by callsigns, but maybe by another acronym. Your FE should define stations with the expected callsign you would search them for

**Comment by pierr3** [comment]
Can confirm this is due to your station database not being properly setup, there is no frequency associated with that callsign, instead just a VCCS table:

```{"id":"cfc30fc4-a8eb-4997-be41-ff6ed452d15c","name":"UUEE_GND","frequency":null,"frequencyAlias":null}```
