### ISSUE TITLE
Wrong radio frequency at EDSB_TWR

### ISSUE THREAD

**Issue by wichtelsbr** [pierr3/VectorAudio#73]
Not sure it is a bug of VectorAudio. But If I log in at EDSB_TWR VectorAudio is tuning to 134.104 instead of 134.105. AudioforVatsim uses the correct frequency.

**Comment by pierr3** [comment]
Thanks for the report, I will investigate. When you tried it, could you still receive and transmit on the correct frequency or not at all? It could be that this is only a display issue.

**Comment by wichtelsbr** [comment]
Last time I tried no one could hear me. But I'm not sure there wasn't any other issue on my side. Will try again and provide feedback.

**Comment by pierr3** [comment]
Did you face this issue again? I have not found any issues in the code so far

**Comment by wichtelsbr** [comment]
just tested it again. Still free. 134.104 instead of 134.105. and no radio contact to other users.

**Comment by pierr3** [comment]
Will be fixed in the next release. in the meantime, if you manually re-add your frequency after deleting the wrong one, it should work
