### ISSUE TITLE
vector audio and TopSky

### ISSUE THREAD

**Issue by MatisseBE** [pierr3/VectorAudio#79]
![image](https://github.com/pierr3/VectorAudio/assets/51272243/d17816fa-9b8d-4e84-8fac-b75df7287a8e)
Wanted to share this issue I saw popping by today.
Is this a fixable issue?

**Comment by pierr3** [comment]
Thanks yes, as explained, AFV Native uses a Windows-only communication layer, which will not be implemented as VectorAudio is cross platform. There is already an API that Juha can use if he wises, and there is already an RDF plugin available on the front page, hence there is nothing to fix.
