### ISSUE TITLE
Retain user settings after upgrade

### ISSUE THREAD

**Issue by dechilders** [pierr3/VectorAudio#8]
Currently, settings are stored in the config.toml file (Stored in /Applications/VectorAudio.app/Contents/Resources/config.toml on macOS). If you upgrade using the dmg installer and drag VectorAudio.app to /Applications, then this file gets deleted when upgrading to a new version of Vector Audio.

The users settings should be retained upon upgrading versions.

**Comment by pierr3** [comment]
This is correct on macOS, the settings file should be stored in Application Support/Vector

**Comment by pierr3** [comment]
Fixed in 0.5.1!
