### ISSUE TITLE
Unable to start a mic test

### ISSUE THREAD

**Issue by Adrian2k** [pierr3/VectorAudio#82]
![image](https://github.com/pierr3/VectorAudio/assets/35482228/f8f61d3e-78ed-4cd0-a0aa-b1c6d0e6ec90)

![image](https://github.com/pierr3/VectorAudio/assets/35482228/ac192093-7e11-41e8-9879-63f35ae75b08)
[vector_audio.log](https://github.com/pierr3/VectorAudio/files/13192498/vector_audio.log)

**Comment by pierr3** [comment]
You will need to set a speaker device too, even if you do not use it!
