### ISSUE TITLE
Unicom and ATIS

### ISSUE THREAD

**Issue by Atriusftw** [pierr3/VectorAudio#84]
I really miss the option to tune and listen to Unicom and ATIS. 
Tuning ATIS is useful as a controller to verify that it is working properly. Listening to Unicom is interesting when handing pilots over in case of no overlaying ATC :)

Would it be possible to implement such a feature?

**Comment by pierr3** [comment]
You can listen to any ATIS if they're properly defined in database by just adding the atis callsign as a station! For unicom this is not possible at the moment

**Comment by Atriusftw** [comment]
> You can listen to any ATIS if they're properly defined in database by just adding the atis callsign as a station!

Ah, guess i'm just unlucky with the stations i'm on. How can i contribute to the database? Here are some that i'm missing in Polaris (Norway FIR):
* ENBR_ATIS: 125.250
* ENVA_ATIS: 127.550
* ENZV_ATIS: 126.000
* ENTC_ATIS: 126.125
* ENBO_ATIS: 123.900
* ENCN_ATIS: 124.475
* ENTO_ATIS: 119.075
* ENRY_ATIS: 136.175


> For unicom this is not possible at the moment

Is this something that would be considered to implement?

**Comment by pierr3** [comment]
> How can i contribute to the database?

You will have to ask who is in charge at your vACC of this, only they have permissions. I did do a quick check and it seems these stations are not defined in database, which would be the issue!

**Comment by pierr3** [comment]
You can listen to unicom by adding a station in the following format "!CALLSIGN" where CALLSIGN is the callsign of the station's location that will be used as a transceiver

**Comment by Atriusftw** [comment]
> You can listen to unicom by adding a station in the following format "!CALLSIGN" where CALLSIGN is the callsign of the station's location that will be used as a transceiver

I'm not sure if i understood this correctly. I tried using the ICAO code of the airport i'm controlling (for example `!ENZV`) and the position (`!ENZV_GND`), but i get the error `Could not find pilot connected under that callsign`

**Comment by pierr3** [comment]
The station or pilot needs to be logged in, just like the error clearly
says ;)

**Comment by Atriusftw** [comment]
> The station or pilot needs to be logged in, just like the error clearly says ;)

Ah, gotcha. I was confused by the station vs pilot here. Indeed works as intended by using the callsign of an actual pilot flying. Thank you so much!
