### ISSUE TITLE
Selecting text channels in ES for activated RX/TX voice channels

### ISSUE THREAD

**Issue by maxlk96** [pierr3/VectorAudio#86]
When using VectorAudio together with Euroscope, it would be nice if the text channels for the activated frequencies gets seleced, as with AFV and the AFV Euroscope Bridge, maybe making VectorAudio compatible with this ES plugin would be an option?

**Comment by pierr3** [comment]
It is unfortunately not possible to make AFV Bridge work with VectorAudio, someone else will have to make a new plugin for that. If someone manifests themselves to do so, I might add the necessary API calls

**Comment by KingfuChan** [comment]
> It is unfortunately not possible to make AFV Bridge work with VectorAudio (it uses Windows only native APIs), someone else will have to make a new plugin for that. If someone manifests themselves to do so, I might add the necessary API calls

Actually my newest version of [RDF](https://github.com/KingfuChan/RDF/releases/tag/v1.3.4) has already realized what AFV does, and is completely safe to replace the whole acv-bridge plugin because the origin one contains some bugs unfixed and it seems not updated for a long time.

**Comment by pierr3** [comment]
Thank you again for your fantastic work, I will edit the readme to make it
more obvious !
