### ISSUE TITLE
Feature Request: Mic & Headset volume in settings

### ISSUE THREAD

**Issue by AS-320** [pierr3/VectorAudio#89]
Greetings,

It would be nice to have a Mic & Headset volume setting that can be manupulated according to the needs.

**Comment by pierr3** [comment]
The headset volume is essentially the "radio gain" slider, although it does also affect speakers.

For microphone volume, you should only use system settings. VectorAudio uses quite a low level API and will accurately pickup your system settings. This also avoids issues we have had in the past with mics being overblown on frequency.
