### ISSUE TITLE
Feature request: allow adding a station that is not in AfV database

### ISSUE THREAD

**Issue by kengreim** [pierr3/VectorAudio#93]
The Audio for Vatsim standalone client allows users to add stations that are not explicitly in the AfV station database, e.g., many ATIS frequencies. If the station isn't in the database, the user is required to input the frequency.

Vector Audio, however, does not allow this. As a controller, it would be helpful to have this feature so that I can check that my ATIS is broadcasting properly.

**Comment by pierr3** [comment]
Unfortunately, this will not be added. The AFV facility manager manual is clear that ALL stations must be added. If your vAcc has not done so, please ensure they do.
