### ISSUE TITLE
Crashes when the connection is a pilot connection

### ISSUE THREAD

**Issue by yanjz124** [pierr3/VectorAudio#94]
If the connection is a pilot connection, Vector Audio will crash immediately after it detects the callsign. The issue exists on both Windows 11 and MacOS 14.2. I tried different callsigns with the same result.
Vector Audio functions as usual if connected as an observer using vPilot.

**Comment by pierr3** [comment]
This is not meant to be used as a pilot audio client. Please refrain from doing so and use the provided pilot clients which do have required support.
