### ISSUE TITLE
Feature request: Multi PTT for different microphones

### ISSUE THREAD

**Issue by TryFanGamer** [pierr3/VectorAudio#96]
I have an ATC mic and sometimes when there is a lot of traffic I like to change to my headset mic and my PTT. a function where you can have 2 PTT for 2 different MIC is a nice to have

**Comment by pierr3** [comment]
Thanks for the suggestion. Unfortunately this out of scope and quite a niche use case, you could use your system settings and a physical PPT on your hardware if you have that.
