### ISSUE TITLE
Unable to open audio devices when using VectorAudio with VoiceMeeter

### ISSUE THREAD

**Issue by neilenns** [pierr3/VectorAudio#98]
Not sure if this will reproduce on other machines, but it does on mine. To reproduce:

1. Install VoiceMeeter Potato
2. Configure it so it uses the Realtek HD Audio 2nd Output for A2
3. Run VectorAudio
4. Configure it so it uses any output for the headset, doesn't seem to matter. I've tried both the Realtek HD Audio 2nd Output and Voicemeeter AUX devices
5. Try and connect

Result: 

```
[2024-01-06 08:59:25.895] [VectorAudio] [info] [afv_native] MiniAudioAudioDevice ERROR: [WASAPI] Failed to initialize device. Device in use.
[2024-01-06 08:59:25.895] [VectorAudio] [info] [afv_native] MiniAudioAudioDevice Error initializing output device: Device or resource busy
[2024-01-06 08:59:25.895] [VectorAudio] [info] [afv_native] afv::ATCClient Unable to open Headset output device.
```

Expect result:

It connects and works.

**Other info**

* If I remove Realtek HD Audio 2nd Output from the VoiceMeeter configuration then VectorAudio can start up fine.
* AFV and vpilot will also crash but only if it is set to use the Realtek HD Audio 2nd Output device. If I configure it to use one of the VoiceMeeter devices it is fine.

**Comment by neilenns** [comment]
I realize this is a funky issue that may be specific to VoiceMeeter + my computer but figured I'd open it anyway. No other apps on my system seem to have issues with VoiceMeeter being installed, e.g. Discord works just fine.

**Comment by pierr3** [comment]
That is likely due to that funky setup. If AudioForVATSIM also faces this issue, try looking at your drivers / reinstall VoiceMeeter, as AudioForVATSIM uses WASAPI without an abstraction layer like I do, it's not likely to be a software issue.

**Comment by neilenns** [comment]
I've tried reinstalling VoiceMeeter probably 10+ times today as part of troubleshooting and no reinstall has helped :(

AFV only crashes if I have Realtek HD Audio 2nd Output device selected as the output. If I point it to one of the VoiceMeeter devices (the normal way I would configure it) it will work fine.

VectorAudio simply won't connect at all. It just fails to initialize.

**Comment by neilenns** [comment]
Installed the latest beta of Voicemeeter today and everything is working fine. Closing this, don't waste your time on it :D
